apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-orders
  namespace: argocd
spec:
  project: default

  # --- MULTI SOURCE ---
  sources:
    # 1) Chart source (APP REPO)
    - repoURL: https://github.com/ravidn1224/ravid-retail-store-app
      targetRevision: main
      path: src/orders/chart
      helm:
        valueFiles:
          - $values/apps/orders/values.yaml

    # 2) Values source (GITOPS REPO)
    - repoURL: https://github.com/ravidn1224/retail-store-gitops
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
